export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE';
export const CREATE_OFFICE_FAILURE = 'CREATE_OFFICE_FAILURE';
export const GET_OFFICE_SUCCESS = 'GET_OFFICE_SUCCESS';
export const GET_OFFICE_FAILURE = 'GET_OFFICE_FAILURE';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
